### ISSUE TITLE
Problem with building latest version of Fauxdacious and update on the m4a file issue

### ISSUE THREAD

**Issue by Sacolevas** [wildstar84/fauxdacious#14]
Hello!!

My apologies, this has been a very busy semester in college and it is not easy for me to answer in time.

Two problems at present (this is Fauxdacious in Linux)

1) M4A  files no playing well with Fauxdacious 

I attach a recording of the m4a file, how it sounds with Fauxdacious, how with Audacious and a text file with the verbose on the FFMPEG version. And also what is the m4a file I use as a sample. 

[Recordings.zip](https://github.com/wildstar84/fauxdacious/files/10975237/Recordings.zip)

2) The latest fauxdacious I compiled was 4.2.1 final, using github build and commands given in the github page (over a year I have used those commands). This version has had some issues never presented before: The M4A problem and also sometimes it freezes and program closes inmediately. 

So I decided to compile the latest version (I use to do this each couple of months aprox), but it is not compiling. 

a) 
Coincidentially in the case of Audacious (which is a player I am not using, but I build the github version and keep the program installed for the sake of comparison and curiosity to see if the program has any progress)  I cannot build either, although the reason is different. Auxdacious build stops with this message: 
 
"error: Missing dependency for Opus support: opus >= 1.0.1 opusfile >= 0.4""

But libopus is installed as well as opus-tools, so I don't know what else it needs to be installed. It is the first time in more than a year that an issue occurs trying to build either fauxdacious or audacious using GIT.

b) In fauxdacious, the problems seems to be bigger, I don't know. I attach the verbose so you can see what might be the reason of the issue. 

[BuildFauxdacious.txt](https://github.com/wildstar84/fauxdacious/files/10975287/BuildFauxdacious.txt)

Thanks for your attention!

**Comment by wildstar84** [comment]
Let's start w/your "build issue":  Since you're having issues building both Fauxd. and Aud., it sounds like your build environment / pkg-config has somehow become foobarred.  Idk the exact procedure you're using, but have you tried:  sudo make distclean, then completely DELETING your fauxdacious_git and fauxdacious-plugins_git directories (where you compiled from, and re-installing everything fresh from git (git clone --single-branch https://github.com/wildstar84/...), and re-running ./autogen.sh, ./configure...?  tinylock.cc has changed since your last successful build, and should be 1606 bytes in size,  tinylock.h should be 1742*.  *There's also a tinylock.h.in that rebuilds tinylock.h when you run autogen.sh and configure!  I've had issues where make distclean didn't seem to remove the libraries in /usr/local/lib/fauxdacious and I had to delete them manually before re-rebuilding (check the dates on them).  What options are you specifying on your ./configure lines?

**Comment by Sacolevas** [comment]
UPDATE!!

With fauxdacious the only new action I took was to disable the valgrind support and suddenly I was able to build the new version (4.4.2). The only warning was the following: 

albumart.cc: In function ‘void* album_helper_thread_fn(void*)’:
albumart.cc:248:20: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
  248 |             system ((const char *) str_concat ({cover_helper, " ALBUM '",
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  249 |                     (const char *) album_buf, "' ", aud_get_path (AudPath::UserDir), " '",
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  250 |                     (const char *) artist_buf, "' '", (const char *) title_buf, "' ",
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  251 |                     (const char *) webfetch}));


HOWEVER .... In the new version the M4A file issue stays the same, it doesn't sound correctly (see the zip file sent in the first message). Still need to test more in order to appreciate if the occasional freezing (when it happens, it lasts for about 10 seconds and then the program closes inmediately) is present. 


Thanks for your attention

**Comment by wildstar84** [comment]
I agree that your "Fauxdacious" "clip" sounded slightly "skippy", but your original song file "1-02 My Sweet Lord.m4a" sounds great (I tried in both Fauxd. & Aud. with no effects plugins in effect and they sound identical to me (though I'm not an audiophyle and have 60+ year old ears)! ;)

**Comment by Sacolevas** [comment]
Hello!

I tested both Audacious and Fauxdacious again. Using both Alsa and PulseAudio plugins, same buffer size of 500ms (as Fauxdacious didn't sound fine I also tried increasing the buffer size with no effect). 

In both, Audacious sound fine (as Fauxdacious sounded fine some time ago ... it is not the most common tracks I play, and about 95% of all my audio files are mp3 files). In both Fauxdacious sounded "skippy"; with the Alsa Plugin was slightly better than PulseAudio which I had as default. 

In order to create the clip files, I used gnome sound recorder, which seems to capture external sound from the speakers, and that is the reason that sounded far away. Now I realize I could have use the recording tool from Audacious and Fauxdacious to create those clips. 

BTW, I don't know if there is a program to record the internal sound no matter what program is playing it (i.e. I could use the recording button from fauxdacious only to record the sound in fauxdacious, not the sound produced with another program).

Thanks for your attention and hopefully the cause of the problem playing those files can be discovered. As I said, not always sounded that way (although I can't recall the exact version the problem started because as I said before those are files that I don't play frequently)

**Comment by wildstar84** [comment]
I'm going to assume that you're using the same buffer-size, equalizer settings, effects plugin settings, other plugins activated, etc. in Fauxd & Aud (but you should still check - comparing apples to apples)!  In Audio (at least for Alsa), make sure you have the same device/mixer & settings set (Fauxdacious has a 2nd device/mixer I added to make my HDMI monitor speakers work).

Just for giggles, try turning OFF the Video-display plugin AND uncheck "Play video stream in popup..." option in the FFmpeg plugion & let me know if that fixes the issue (since with those off, we should be essentially just doing what Audacious does, and could narrow down where we could have introduced some inefficiencies.

Also, I released a minor new commit involving ffaudio just today (which mostly involves video play / video window placement), just to be fully up-2-date.  Most ffaudio-changes in the past year are in the video-playing code.

**Comment by Sacolevas** [comment]
Hello,

I followed those instructions and unckeck things, but made no difference. Actually I tried disabling the FFMEG plugin and played the same way, so it is not clear to me if that plugin is the one acting or which input plugin is acting when this file is played

A attach config files for Audacious and Fauxdacious

[config_fauxdacious.zip](https://github.com/wildstar84/fauxdacious/files/10986540/config_fauxdacious.zip)
[config_audacious.zip](https://github.com/wildstar84/fauxdacious/files/10986541/config_audacious.zip)

**Comment by wildstar84** [comment]
I don't see anything amiss in config except Fauxd has "net_buffer_kb=1024" (no config for Aud).  You might try running both witn "-V" to see which plugin each is using to play the file & see if they're the same or different.  Other than that, I don't know.  Perhaps try converting it to mp3 directly, ie. "ls '1-02 My Sweet Lord.m4a' | fauxdacious -DcH --out=mp3 - >'/tmp/1-02 My Sweet Lord.mp3'" to have Fauxdacious convert it to mp3, then play that file & see if it sounds better?

**Comment by wildstar84** [comment]
Closing due to lack of further feedback, assuming resolved.
