### ISSUE TITLE
Feature request: Album list

### ISSUE THREAD

**Issue by daemonspudguy** [wildstar84/fauxdacious#15]
Since Audacious will never implement an ability to choose and listen to an album specifically, I think it would be a potentially useful feature for Fauxdacious.

**Comment by wildstar84** [comment]
Can you better describe how this would work?  I'm guessing by "album" you're referring to "all songs in a directory and it's subdirectories whose album tag==<album>"?  Also note that Fauxdacious has already extended the "Search & Select" feature to find and select for play all songs (in the playlist) by album (or other) tag(s).

**Comment by daemonspudguy** [comment]
That is correct. And yes, there was.

**Comment by daemonspudguy** [comment]
https://redmine.audacious-media-player.org/boards/1/topics/795?r=817

**Comment by daemonspudguy** [comment]
How do I configure the Ampache plugin?

**Comment by wildstar84** [comment]
You'll first need to install Ampache browser (https://ampache-browser.org/) and pbly this (Ampache server:  https://ampache.org/), then rerun autogen.sh and configure in fauxdacious-plugins.  The configure script should then tell you whether you have the ampache libs (dependency) installed successfully.  If so, rebuild (make).  I can't remember if you also then need to go to fauxdacious-plugins/src/ampache/ and run make & make install manually from there or not.  Sorry, but it's been over 5 years since I last installed this (on another box) to test the plugin when Audacious first released it, but I do recall that it did work in Fauxdacious in my testing (after I filed a bug to Audacious regarding it & they fixed)!

**Comment by wildstar84** [comment]
Now, after dusting this thing off, it appears that I just tested the plugin without ever installing and setting up an Ampache SERVER, b/c ampache-browser has a "demo server" mode, but you would have to set up a local server with your music to use your music.  At least though, you could build w/the browser plugin (and try out with there demo albums, which do actually play) and see if that'll actually do what you want before going thru the bother of installing & setting up a local server for your music.

**Comment by daemonspudguy** [comment]
I have done that. It kind of works but is prone to crashing, got some reason.

**Comment by wildstar84** [comment]
You might try it using the latest version of real Audacious & see if it's "crashy" there (They do have a recent Ampache commit that I haven't merged yet).  If so, report a bug there (and I'll merge there fix, if any), if not then perhaps I need to take another look at it, but in that case I don't hold out much hope in that I don't use Ampache (a separate program) and haven't touched it in years.

**Comment by daemonspudguy** [comment]
I've long since switched back to DeaDBeeF and forgot this existed. I'm gonna close it.
