### ISSUE TITLE
Request: an AUR package

### ISSUE THREAD

**Issue by Hunanbean** [wildstar84/fauxdacious#7]
It would be nice to see this software as an easily installable/buildable AUR package.

Thanks

**Comment by wildstar84** [comment]
Yes it would (been on the TODO for a long time now)  I started to look into it awhile back, but got lost in the massive learning curve - Audacious has this broken out into several packages & Debian requires separate corresponding SRC pkgs, so I kinda gave up at the time, especially since I've so far heard zero feedback on the "easy-install" binary Windows package I created!  If you or anyone you know knows how to accomplish this or contribute to it, then I'm all ears! ;)

**Comment by hello-world-dot-c** [comment]
Just came here to let you know that your easy-install binary Windows package works GREAT! Perhaps showing it (off ;-) more prominently on the fauxdacious main page and in the github readme would help? It took me a while to find it, only after reading about it here. Before I tried to build it in Xubuntu but it failed with some package not available error.
Was looking for something that could play the radio.net channels, and that, too, works great, once you've worked through the FAQ on the topic.
Thanks, and keep up the good work!

**Comment by wildstar84** [comment]
Thanks for reporting!  I've added it near the top of the README, and it is mentioned in the main page, and in the FAQ (#3).
