### ISSUE TITLE
Greetings and a couple of small Issues in Windows and Linux

### ISSUE THREAD

**Issue by Sacolevas** [wildstar84/fauxdacious#8]
Hello Again!

It has been a while (about six months) since the last time I wrote to report issues using Fauxdacious. Of course it is because at least for my everyday usage (not a power user who test all features, but everyday Fauxdacious is the only music player I currently use in Linux) everything works fine. Just a couple of small issues I came here:

1) The LyricsHelper has a small problem when fetching Lyrics from Genius.com which is the presence of this additional text at the end of the song: "Embed Cancel How to Format Lyrics: Type out all lyrics, even if it’s a chorus that’s repeated throughout the song The Section Header button breaks up song sections. Highlight the text then click the link Use Bold and Italics only to distinguish between different singers in the same verse. E.g. “Verse 1: Kanye West, Jay-Z , Both ” Capitalize each line To move an annotation to different lyrics in the song, use the [...] menu to switch to referent editing mode". Of course it is not a big deal because you still see the right lyrics at the beginning, but it would be better to not see that long message if possible. 

2) I use Linux almost everyday. Some days I have to use Windows and of course I have installed the latest version of Fauxdacious for Windows (the issue in (1) also applies for Windows). The big problem for the Windows operating system is that for some reason (also applies to Audacious, for example ... I checked to see if the problem was Fauxdacious exclusive or not) if I am listening to music and at the same time using other programs with moderate CPU use (about 70%), Fauxdacious freezes completely (even if I close that other program, the freeze continues). This problem doesn't happen with Windows exclusive players like Foobar2000, for example or Cross Platform media players like SMPlayer (which I use for videos), I wonder why. 

Thanks for everything and your excellent program!

**Comment by wildstar84** [comment]
1)  Fixed - upgrade LyricFinder to v1.22 (Linux - Windows is bundled w/.exe, so only can be updated by new Fauxdacious for Windows release, so it may be awhile - unless you want to install Strawberry Perl for Windows and use the perl module (.pl) versions of the helper scripts and their required modules).  Seems like Genius has added some SPAM!  Thanks for reporting!

2)  Does the audio playback freeze, or just the interface?  Yes, the interface seems to sometimes freeze in Windows, likely due to the crappy way Windows emulates posix threading, etc.  If it's also happening in Aud, you might want to put a bug in their ear (make sure you're testing the latest Aud. release), as they are alot more proficient in this level of programming, particularly on Windows, as I almost never use Windows (except building new Fauxd. releases on "final" (non-beta) versions)! ;)

You are most welcome, and thanks for using it & alerting me to the Genius spam!

Jim

**Comment by wildstar84** [comment]
Closing - assuming fixed due to lack of further correspondance.
